### ISSUE TITLE
Things to change for the results file

### ISSUE THREAD

**Issue by annamost** [yaksilab/Javid_S2P_codes#1]
Metadata to add: 
name of the exp, ..dimensions and frame rate 

Get rid of plane 8 (last plane that is crocked)

reindex the neurons/identifiers so they match after you reorganised the planes 

add comments: 
- people need to copy the config file into the suite2p dir
- does not work for under 4 planes (but of course one plane)
- tell people that you need to look at the gui to find the cells

**Comment by javidaf** [comment]
This issue has been resolved now!
